# Generated by Django 4.1.3 on 2022-12-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="intbl_purchaserequisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IDIntbl_PurchaseRequisition", models.IntegerField()),
                ("RequisitionType", models.CharField(max_length=50)),
                ("Date", models.CharField(max_length=100)),
                ("TotalAmount", models.FloatField()),
                ("TaxAmount", models.FloatField()),
                ("Company_Name", models.CharField(max_length=200)),
                ("State", models.CharField(max_length=200)),
                ("ReceivedDate", models.CharField(max_length=200)),
                ("purchaseBillNumber", models.IntegerField()),
                ("DiscountAmount", models.FloatField()),
                ("Outlet_Name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="intbl_purchaserequisition_contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "IDIntbl_PurchaseRequisition_Contract",
                    models.CharField(max_length=200),
                ),
                ("ItemID", models.IntegerField()),
                ("UnitsOrdered", models.IntegerField()),
                ("PurchaseReqID", models.IntegerField()),
                ("Rate", models.FloatField()),
                ("Name", models.CharField(max_length=200)),
                ("BrandName", models.CharField(max_length=200)),
                ("Code", models.CharField(max_length=200)),
                ("UOM", models.CharField(max_length=200)),
                ("StockType", models.CharField(max_length=200)),
                ("Department", models.CharField(max_length=200)),
                ("GroupName", models.CharField(max_length=200)),
                ("ExpDate", models.CharField(max_length=200)),
                ("Status", models.CharField(max_length=200)),
                ("Taxable", models.CharField(max_length=200)),
            ],
        ),
    ]
