# Generated by Django 4.1.3 on 2022-12-06 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intbl_purchaserequisition",
            name="id",
        ),
        migrations.AlterField(
            model_name="intbl_purchaserequisition",
            name="IDIntbl_PurchaseRequisition",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="intbl_purchaserequisition_contract",
            name="PurchaseReqID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.intbl_purchaserequisition",
            ),
        ),
    ]
